### ISSUE TITLE
Unhandled rejection Error: SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by daswars** [onedr0p/telegram-sonarr-bot#22]
Unhandled rejection Error: SyntaxError: Unexpected token <
    at /app/sonarr.js:63:11
    at tryCatcher (/app/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/app/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/app/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/app/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/app/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:384:17)

With the docker-compose file the bot generate no config file...
docker-compose.yml
telegram-sonarr-bot:
  build: /home/git/telegram-sonarr-bot/.
  restart: always
  hostname: telegram-sonarr-bot
  links:
    - sonarr
  environment:
    - TELEGRAM_BOTTOKEN=XXXXXXXXXXXXXXXXXXXXXXX
    - BOT_PASSWORD=access
    - BOT_OWNER=
    - SONARR_HOST=sonarr
    - SONARR_APIKEY=XXXXXXXXXXXXXXXXXXXXXXX
    - SONARR_PORT=5050
    - SONARR_URLBASE=
    - SONARR_SSL=false
    - SONARR_USERNAME=user
    - SONARR_PASSWORD=password

**Comment by onedr0p** [comment]
I'm curious, does this work for you without using docker?

I don't use docker, but I'll test it out again.

**Comment by onedr0p** [comment]
This looks like it's a problem with you Telegram token, make sure you use the full key, it should look like `135128375:AAGtdTtOTnfH9eTa6kmdlQYTs-C4sryRNDA`

**Comment by onedr0p** [comment]
Any update? I'll close this issue in a couple days unless you're still having a problem.

**Comment by onedr0p** [comment]
Closing.
