### ISSUE TITLE
Stopped running on Synology

### ISSUE THREAD

**Issue by kstanleyadams** [onedr0p/telegram-sonarr-bot#26]
node sonarr.js
/volume1/custom/telegram-sonarr-bot/sonarr.js:29
class Response {
^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

Any ideas why?

**Comment by onedr0p** [comment]
What node version are you running?

**Comment by kstanleyadams** [comment]
I am running the latest version on the synology package centre (0.12.6-0112).

**Comment by onedr0p** [comment]
It looks like you might need to get the node version updated to the LTS release (4.2.X). Theres a small fix i can make though.

**Comment by kstanleyadams** [comment]
Is it a simple fix? Most Synology NAS users will be running < 4.x.

**Comment by onedr0p** [comment]
Very simple, I'm busy at the moment but ill push an update in a few hours and reply here when done.

**Comment by onedr0p** [comment]
Fixed in latest commit, let me know if that solves your problem!

**Comment by kstanleyadams** [comment]
Just tried the latest committ:

node sonarr.js
2016-01-12T20:45:44.986Z - info: config file found /volume1/custom/telegram-sonarr-bot/lib/../config.json
2016-01-12T20:45:45.001Z - info: config file not found
2016-01-12T20:45:45.139Z - info: acl file found /volume1/custom/telegram-sonarr-bot/lib/../acl.json
/volume1/custom/telegram-sonarr-bot/node_modules/sonarr-api/lib/api.js:45
  if (this.apiKey.search(/[^a-z0-9]{32}/) !== -1) {
                 ^
TypeError: Cannot read property 'search' of undefined
    at new SonarrAPI (/volume1/custom/telegram-sonarr-bot/node_modules/sonarr-api/lib/api.js:45:18)
    at Object.<anonymous> (/volume1/custom/telegram-sonarr-bot/sonarr.js:24:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by onedr0p** [comment]
Make sure you're config file is correct. Copy it from the template again and paste in the values in the quotes

**Comment by kstanleyadams** [comment]
Oops. Fixed. Thanks!
