### ISSUE TITLE
Using an IP address as the hostname does not work

### ISSUE THREAD

**Issue by kstanleyadams** [onedr0p/telegram-sonarr-bot#27]
node sonarr.js
/Users/Kevin/Desktop/telegram-sonarr-bot/node_modules/sonarr-api/lib/api.js:45
  if (this.apiKey.search(/[^a-z0-9]{32}/) !== -1) {
                 ^

TypeError: Cannot read property 'search' of undefined
    at new SonarrAPI (/Users/Kevin/Desktop/telegram-sonarr-bot/node_modules/sonarr-api/lib/api.js:45:18)
    at Object.<anonymous> (/Users/Kevin/Desktop/telegram-sonarr-bot/sonarr.js:44:14)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3

**Comment by onedr0p** [comment]
That error is for the sonarr apiKey. Make sure it's set correctly.

**Comment by kstanleyadams** [comment]
I have discovered the issue. For some reason, my computer types different quote characters (“”, rather than ""), which subsequently caused the config file to stop reading correctly.

**Comment by onedr0p** [comment]
This has been an issue for a few users, I'll try to implement a way to check the config for these utf8 quote characters
