### ISSUE TITLE
upcoming not working anymore

### ISSUE THREAD

**Issue by aroundmyroom** [onedr0p/telegram-sonarr-bot#44]
just made a new git clone to see if it is related to my version but upcoming is broken in my environment

2016-04-13T19:09:02.053Z - info: user: AroundMyRoom, message: found the following series 2016-04-13 - Rosewood,2016-04-13 - The Middle,2016-04-13 - Rogue,2016-04-13 - Empire (2015),2016-04-13 - The Americans (2013),2016-04-13 - Broad City,2016-04-13 - Underground,2016-04-13 - Criminal Minds: Beyond Borders, ,2016-04-14 - Houdini & Doyle,2016-04-14 - Bones,2016-04-14 - DC's Legends of Tomorrow - *Done*,2016-04-14 - The Odd Couple (2015),2016-04-14 - The Blacklist,2016-04-14 - The 100,2016-04-14 - Mom,2016-04-14 - 2 Broke Girls,2016-04-14 - Game of Silence,2016-04-14 - Orphan Black,2016-04-14 - The Catch,2016-04-14 - Vikings,2016-04-14 - Rush Hour (2016), ,2016-04-15 - Unbreakable Kimmy Schmidt,2016-04-15 - Unbreakable Kimmy Schmidt,2016-04-15 - Unbreakable Kimmy Schmidt,2016-04-15 - Unbreakable Kimmy Schmidt,2016-04-15 - Unbreakable Kimmy Schmidt,2016-04-15 - Unbreakable Kimmy Schmidt,2016-04-15 - Unbreakable Kimmy Schmidt,2016-04-15 - Unbreakable Kimmy Schmidt,2016-04-15 - Unbreakable 
Kimmy Schmidt,2016-04-15 - Unbreakable Kimmy Schmidt,2016-04-15 - Unbreakable Kimmy Schmidt,2016-04-15 - The Vampire Diaries,2016-04-15 - Bitten,2016-04-15 - Slasher,2016-04-15 - Shark Tank,2016-04-15 - The Originals,2016-04-15 - Banshee,2016-04-15 - Wynonna Earp
2016-04-13T19:09:02.129Z - warn: user: AroundMyRoom message: 400 {"ok":false,"error_code":400,"description":"[Error]: Bad Request: Field \"keyboard\" of the ReplyKeyboardMarkup should be an Array"}

2016-04-13T19:09:02.129Z - warn: user: AroundMyRoom message: 400 {"ok":false,"error_code":400,"description":"[Error]: Bad Request: Field \"keyboard\" of the ReplyKeyboardMarkup should be an Array"}
Unhandled rejection Error: 400 {"ok":false,"error_code":400,"description":"[Error]: Bad Request: Can't parse message text: Can't find end of the entity starting at byte offset 22"}
    at /home/dennis/t2/telegram-sonarr-bot/node_modules/node-telegram-bot-api/src/telegram.js:121:15
    at tryCatcher (/home/dennis/t2/telegram-sonarr-bot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/dennis/t2/telegram-sonarr-bot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/home/dennis/t2/telegram-sonarr-bot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/home/dennis/t2/telegram-sonarr-bot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/home/dennis/t2/telegram-sonarr-bot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/dennis/t2/telegram-sonarr-bot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/dennis/t2/telegram-sonarr-bot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/async.js:15:14)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)

**Comment by jpartain89** [comment]
I can second this error myself!

`2016-04-14T11:40:54.967Z - info: user: jpartain89, message: sent '/upcoming' command from 2016-04-14T11:40:54.961Z to 2016-04-17T11:40:54.964Z
2016-04-14T11:40:56.458Z - info: user: jpartain89, message: found the following series 2016-04-14 - The 100,2016-04-14 - Archer (2009),2016-04-14 - The Daily Show,2016-04-14 - The Nightly Show with Larry Wilmore,2016-04-14 - @midnight, ,2016-04-15 - Unbreakable Kimmy Schmidt,2016-04-15 - Unbreakable Kimmy Schmidt,2016-04-15 - Unbreakable Kimmy Schmidt,2016-04-15 - Unbreakable Kimmy Schmidt,2016-04-15 - Unbreakable Kimmy Schmidt,2016-04-15 - Unbreakable Kimmy Schmidt,2016-04-15 - Unbreakable Kimmy Schmidt,2016-04-15 - Unbreakable Kimmy Schmidt,2016-04-15 - Unbreakable Kimmy Schmidt,2016-04-15 - Unbreakable Kimmy Schmidt,2016-04-15 - Unbreakable Kimmy Schmidt,2016-04-15 - Unbreakable Kimmy Schmidt,2016-04-15 - Unbreakable Kimmy Schmidt,2016-04-15 - The Graham Norton Show
2016-04-14T11:40:57.010Z - warn: user: jpartain89 message: 400 {"ok":false,"error_code":400,"description":"[Error]: Bad Request: Field \"keyboard\" of the ReplyKeyboardMarkup should be an Array"}
Unhandled rejection Error: 400 {"ok":false,"error_code":400,"description":"[Error]: Bad Request: Can't parse message text: Can't find end of the entity starting at byte offset 22"}
    at /home/jpartain89/git/telegram-sonarr-bot/node_modules/node-telegram-bot-api/src/telegram.js:121:15
    at tryCatcher (/home/jpartain89/git/telegram-sonarr-bot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/jpartain89/git/telegram-sonarr-bot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/home/jpartain89/git/telegram-sonarr-bot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/home/jpartain89/git/telegram-sonarr-bot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/home/jpartain89/git/telegram-sonarr-bot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/jpartain89/git/telegram-sonarr-bot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/jpartain89/git/telegram-sonarr-bot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)`

I don't think I have any personally identifiable info in there, or anything that can assist too much in someone breaking my systems! But hope this can help you out!

**Comment by crxdelsol** [comment]
I have fixed this just now in pull request #45. Waiting for @onedr0p to accept it.

**Comment by jayrox** [comment]
merged in #45

**Comment by aroundmyroom** [comment]
fixed .. thanks !
