### ISSUE TITLE
Bad Request: Field \"keyboard\" of the ReplyKeyboardMarkup should be an Array

### ISSUE THREAD

**Issue by nicovs** [onedr0p/telegram-sonarr-bot#48]
Hi, I get this error wen using the sonarr-bot.
Using couchpotato bot as well, and no issues there.

```
Unhandled rejection Error: 400 {"ok":false,"error_code":400,"description":"[Error]: Bad Request: Field \"keyboard\" of the ReplyKeyboardMarkup should be an Array"}
    at /home/nicovs/telegram-sonarr-bot/node_modules/node-telegram-bot-api/src/telegram.js:121:15
    at tryCatcher (/home/nicovs/telegram-sonarr-bot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/nicovs/telegram-sonarr-bot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/home/nicovs/telegram-sonarr-bot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/home/nicovs/telegram-sonarr-bot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/home/nicovs/telegram-sonarr-bot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/nicovs/telegram-sonarr-bot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/nicovs/telegram-sonarr-bot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

Some more info:
Running on Ubuntu.

```
node --version
v4.4.3

nodejs --version
v4.4.3

pm2 -v
1.1.2
```

**Comment by aroundmyroom** [comment]
how to reproduce?

**Comment by nicovs** [comment]
In telegram om my laptop i just do a / command

eg: 
`/q orange`

then I get no response in Telegram, but i mentioned error output from above.

However, the bot is talking to me about imported series:
https://cloudup.com/cSwdzWVzSZQ

**Comment by ste7enm** [comment]
I'm getting a similar issue, but for me I can search for a new series (getting a response), but can't run other random commands like /help and /users and /wanted and /rss and /refresh.

Here's my output from /help, for example:

> 2016-06-22T03:54:29.136Z - info: user: 21025499, message: sent '/help' command
> Unhandled rejection Error: 400 {"ok":false,"error_code":400,"description":"Bad Request: Can't parse message text: Can't find end of the entity starting at byte offset 13"}
>     at /home/seven/telegram-sonarr-bot/node_modules/node-telegram-bot-api/src/telegram.js:121:15
>     at tryCatcher (/home/seven/telegram-sonarr-bot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/util.js:26:23)
>     at Promise._settlePromiseFromHandler (/home/seven/telegram-sonarr-bot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/promise.js:507:31)
>     at Promise._settlePromiseAt (/home/seven/telegram-sonarr-bot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/promise.js:581:18)
>     at Promise._settlePromises (/home/seven/telegram-sonarr-bot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/promise.js:697:14)
>     at Async._drainQueue (/home/seven/telegram-sonarr-bot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/async.js:123:16)
>     at Async._drainQueues (/home/seven/telegram-sonarr-bot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/async.js:133:10)
>     at Async.drainQueues (/home/seven/telegram-sonarr-bot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/async.js:15:14)
>     at process._tickCallback (node.js:415:13)

I also get the \"keyboard\" error specifically for other commands, like /refresh.

**Comment by hashworks** [comment]
I get this for all commands that access Sonarr, /library, /query, /upcoming. node v6.5.0.

**Comment by onedr0p** [comment]
I wonder if this is a issue with node 6. Node 4.x seems to be unaffected.

**Comment by UiharuKazari2008** [comment]
Same here with Debian 8 and Node 4.6.1 fresh install

**Comment by ste7enm** [comment]
Mine will not tell me it's added a new series through the search successfully, but the series isn't there when I check Sonarr.

**Comment by schumi2004** [comment]
Reporter said he was running version 4.4.3, i'm running node version 4.6.0.
Seeing this issue i tested adding a serie and got no issues, bot/sonarr functions perfectly fine.

**Comment by ste7enm** [comment]
(Not = Now above, autocorrect and no edit...) 

@schumi2004, can you run the other bot commands successfully too?

**Comment by schumi2004** [comment]
All commands tested successfully, /start, help, query, library, upcoming, wanted 

MyBot:
Series "The Missing" added

/library missing
[3:10:36 PM] MyBot:
Found matching results in Sonarr library:
The Missing

**Comment by ste7enm** [comment]
Hm. I updated to Node v7.0.0 and updated to the latest version of the bot and when I ran /help, I still got this: 

`Unhandled rejection Error: 400 {"ok":false,"error_code":400,"description":"Bad Request: Can't parse message text: Can't find end of the entity starting at byte offset 13"}
    at /home/seven/telegram-sonarr-bot/node_modules/node-telegram-bot-api/src/telegram.js:121:15
    at tryCatcher (/home/seven/telegram-sonarr-bot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/seven/telegram-sonarr-bot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/home/seven/telegram-sonarr-bot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/home/seven/telegram-sonarr-bot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/home/seven/telegram-sonarr-bot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/seven/telegram-sonarr-bot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/seven/telegram-sonarr-bot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
`

**Comment by bouncintigger** [comment]
I am seeing the same issues with node 6.9.2, but it was working perfectly for 24 hours and a couple of dozen /query commands before failings.

**Comment by bouncintigger** [comment]
Just upgraded to 7.4.0.... still broken :(

**Comment by schumi2004** [comment]
Permission issue maybe?
