### ISSUE TITLE
Error 400 various commands

### ISSUE THREAD

**Issue by aroundmyroom** [onedr0p/telegram-sonarr-bot#61]
using /rss /wanted /refresh
etc.. 

2016-12-02T18:04:14.886Z - warn: user: xxx, message: 400 {"ok":false,"error_code":400,"description":"Bad Request: Field \"keyboard\" of the ReplyKeyboardMarkup should be an Array"}
Unhandled rejection Error: 400 {"ok":false,"error_code":400,"description":"Bad Request: Can't parse message text: Can't find end of the entity starting at byte offset 22"}
    at /home/xx/Telegram/node_modules/node-telegram-bot-api/src/telegram.js:121:15
    at tryCatcher (/home/xx/Telegram/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/xx/Telegram/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/home/xx/Telegram/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/home/xx/Telegram/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/home/xx/Telegram/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/xx/Telegram/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/xx/Telegram/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/async.js:15:14)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)

**Comment by RPWouters** [comment]
Same problem here running on my NetGear NAS. Don't have the problem when I run it on my PC.
