### ISSUE TITLE
adding show error

### ISSUE THREAD

**Issue by aroundmyroom** [onedr0p/telegram-sonarr-bot#63]
tried to add a show... 

2018-01-18T11:59:27.618Z - info: user: blabla, message: looking for existing series
2018-01-18T11:59:28.066Z - info: user: The X-Files - 1993, message: confirm correct show: Blabla
2018-01-18T11:59:28.165Z - warn: user: Blabla, message: 400 {"ok":false,"error_code":400,"description":"Bad Request: can't parse entities in message text: Can't find end of the entity starting at byte offset 22"}
Unhandled rejection Error: 400 {"ok":false,"error_code":400,"description":"Bad Request: can't parse entities in message text: Can't find end of the entity starting at byte offset 22"}
    at /home/bla/Telegram/node_modules/node-telegram-bot-api/src/telegram.js:121:15
    at tryCatcher (/home/bla/Telegram/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/bla/Telegram/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/home/bla/Telegram/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/home/bla/Telegram/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/home/bla/Telegram/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/bla/Telegram/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/bla/Telegram/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/async.js:15:14)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)

**Comment by RPWouters** [comment]
Same problem here running on my NetGear NAS. Don't have the problem when I run it on my PC.
